# Database Connection Settings
# If DB_HOST environment variable is missing, it defaults to 'localhost'
# If DB_PORT environment variable is missing, it defaults to '5433'
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/store
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

